<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <link rel="stylesheet" href="dayOrganizer.css">
</head>

<body>
    <div class "header">
        <h3>Stud Organizer</h3>
        <hr>
    </div>
    <div class = "main">
        <h1 style = "display:inline-block; ">Суббота</h1>
        <p style = "display:inline-block; padding-left: 10px;">Неделя 1</p>

        <hr>
        <h2>Расписание</h2>


    </div>

    </body>
</html>